version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: America/New_York
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10