name: Specs
on:
  workflow_call:
    secrets:
      TRUSONA_TOKEN:
        required: true
      TRUSONA_SECRET:
        required: true
      BUSTER_USERNAME:
        required: true
      BUSTER_PASSWORD:
        required: true
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      TRUSONA_ENDPOINT: https://api.staging.trusona.net
      BUSTER_BASE_URL: https://buster.staging.trusona.net
      TRUSONA_TOKEN: ${{ secrets.TRUSONA_TOKEN }}
      TRUSONA_SECRET: ${{ secrets.TRUSONA_SECRET }}
      BUSTER_USERNAME: ${{ secrets.BUSTER_USERNAME }}
      BUSTER_PASSWORD: ${{ secrets.BUSTER_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: yarn
    - run: |
        yarn install
        npm run test
